project_id = "tjnqelwplalrsepzqotb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.mock-bankid]
verify_jwt = false